### ISSUE TITLE
Why using sub-crates instead of rust modules

### ISSUE THREAD

**Issue by tdaron** [rumpl/miniwm#1]
Hi !

I hope i am not getting interested too late in your article/repo haha !

I was wondering, why are you using sub-creates instead of sub-modules? Is is just personal preference ?

**Comment by rumpl** [comment]
Hey, glad you are interested in this, by "sub-modules" you mean git sub-modules or the Cargo ones? 

I actually don't have a preference and if memory serves me well, at the time I wrote this I didn't know really how sub-modules worked 😅 

If you want to contribute and have fun go ahead, I wouldn't mind a PR that would use sub-modules :)

**Comment by tdaron** [comment]
haha yes i am talking about rust modules system :) 

thanks for the fast answer !

**Comment by tdaron** [comment]
(and btw, do you know where i can find the constant XC_LEFT_PTR in x11 crate ? i struggled a lot on this to give user a cursor at startup of the wm and i ended hardcoding it in my code )
